# Generated by Django 5.2 on 2026-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_remove_comment_task_board_description_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('await_feedback', 'Await Feedback'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
